name: "Adam Morgan"
markdown: redcarpet
highlighter: pygments
permalink: :title
exclude: [README.md, LICENSE, Makefile]

# Information for the Atom feed
gereksiz:
   author: "Adam Morgan"
   email: "atom.morgan@gmail.com"
